### ISSUE TITLE
Hard Disk

### ISSUE THREAD

**Issue by madmax01** [mintsoft/check_supermicro_superdoctor#1]
Hello,

Nice Script. would it be possible also to add the "Hard disk" into the Check. As once i check the SupmermicroDoctor  i see also the Harddisk. (Raid Volume)

thx

Max

**Comment by mintsoft** [comment]
Hi @madmax01 

Apologies for the delay; it should be checking harddisks as long as the raid controller is supporter by super doctor (https://github.com/mintsoft/check_supermicro_superdoctor/blob/master/check_supermicro_superdoctor.pl#L121)

We use AOC-SAS2LP-H8IR-16DD in ours and they show up

Thanks,
Rob

**Comment by madmax01** [comment]
He Rob,

Sry if i start the Script i get just. don't see any Info regarding Disk.   if i open the Doctor then i see the the Raid.  So it's recognizing it.  or is it covering the check - but not giving Output for? i use an Supported Configuration based on SYS-5038MR-H8TRF



OK | 'CPU Temp'=39C;; 'PCH Temp'=44C;; 'System Temp'=28C;; 'Peripheral Temp'=39C;; 'VcpuVRM Temp'=36C;; 'VmemABVRM Temp'=37C;; 'VmemCDVRM Temp'=36C;; 'P1-DIMMA1 Temp'=35C;; 'P1-DIMMB1 Temp'=36C;; 'P1-DIMMC1 Temp'=33C;; 'P1-DIMMD1 Temp'=34C;; FAN=3200RPM;; 12V=11937mV;; 5VCC=5026mV;; 3.3VCC=3299mV;; VBAT=2998mV;; Vcpu=1818mV;; VDIMMAB=1182mV;; VDIMMCD=1182mV;; 5VSB=4974mV;; 3.3VSB=3248mV;; '1.5V PCH'=1509mV;; '1.2V BMC'=1227mV;; '1.05V PCH'=1050mV;; 'PS Status'=0N/A;;

**Comment by mintsoft** [comment]
@madmax01 Hiya, there wouldn't be any perfdata output for the disks (as there's nothing really useful to graph), although if they (physical or virtual disk) end up in a non-optimal state then the check will change status: 
https://github.com/mintsoft/check_supermicro_superdoctor/blob/master/check_supermicro_superdoctor.pl#L122
https://github.com/mintsoft/check_supermicro_superdoctor/blob/master/check_supermicro_superdoctor.pl#L126

**Comment by madmax01** [comment]
Hi there ;) Merry Christmas afterwards ;)

thx for the Info. yes for Perfdata makes no sense.  but what i wanted to test is to get the Status of the Raid Volume and the Physically Disks. wanted to check if they are recognized.  

But i'am not very familiar with that Kind of Script. doing often simple bash scripts ;)

i would be happy if you could let me know how i would Need to Change the Script beeing able to manually check the Status of Raid + Physically Disks ;). so to see the Amount of it etc,.... ;)

many thx


Max

**Comment by madmax01** [comment]
today i just checked the OID with snmpwalk.  i don't get any Infos back from

$RAIDVirtualDiskTree="1.3.6.1.4.1.10876.100.1.11.1";
$RAIDPhysicalDiskTree="1.3.6.1.4.1.10876.100.1.12.1";

for cpu etc,,  i see the Infos.

So it seems that this OID's are not Unique.

thinking this ID's related to LSI Cards which you using above.  based on my supermicro i use the Default embedded  Fake-Raid (RSTE).  

if i query the Enterprise ones i checked the Name which i see on Supermicro

1.3.6.1.4.1.10876.100.1.4
SNMPv2-SMI::enterprises.10876.100.1.4.1.1.1 = STRING: "Volume0"
SNMPv2-SMI::enterprises.10876.100.1.4.1.2.1 = STRING: "\\\\.\\PHYSICALDRIVE0"
SNMPv2-SMI::enterprises.10876.100.1.4.1.4.1 = INTEGER: 0
SNMPv2-SMI::enterprises.10876.100.1.4.1.5.1 = STRING: "Intel Raid 1 Volume"
SNMPv2-SMI::enterprises.10876.100.1.4.1.6.1 = INTEGER: 724878
SNMPv2-SMI::enterprises.10876.100.1.4.1.8.1 = STRING: "Fixed hard disk media"
SNMPv2-SMI::enterprises.10876.100.1.4.1.9.1 = STRING: "SCSI"
SNMPv2-SMI::enterprises.10876.100.1.4.1.10.1 = STRING: "Intel(R) C600+/C220+ series chipset SATA RAID Controller"

So i guess  "4"   is the Status for the Volume.  6 seems is the Size.

How could i check what is behind the "0" ?.  in youre script you found the Columns

thx

Max

**Comment by mintsoft** [comment]
Hiya @madmax01 

Thanks for the additional information, the oids you've mentioned there are used for generic harddisks through the software raid, rather than the hardware raid (which is what `$RAIDVirtualDiskTree` and `$RAIDPhysicalDiskTree` are checking). From the description "Intel Raid 1 Volume" you can see that it's software raid rather than hardware raid. For monitoring these you'll probably be better off with something like https://exchange.nagios.org/directory/Plugins/Hardware/Storage-Systems/RAID-Controllers/check_intel_raid/details as I'm not really planning to add software raid monitoring.

Hope that helps!

**Comment by madmax01** [comment]
Hi there,

thx. i found out info for it.   0= ok.  1 = warning. 2 = critically ;).  all good. i will stick with snmp for it and changing the script slightly ;)

Pitty it is but supermicro is not supporting LSI for each Model ;(. therefore best case is Intel Raid.

thx for youre Support.  

Have a good new Year ;)

Best regards

Max
