### ISSUE TITLE
AllStatus Monitoring

### ISSUE THREAD

**Issue by madmax01** [mintsoft/check_supermicro_superdoctor#2]
Hello,

i'am not sure what i'am doing wrong.

i wanted to change the Script to get the "AllStatus" overally for the Sensors.

once in do snmpwalk .1.3.6.1.4.1.10876.2  i get the following below

SNMPv2-SMI::enterprises.10876.2.2 = INTEGER: 0
SNMPv2-SMI::enterprises.10876.2.3 = STRING: "No problem."

i tried now to add this to the Script. i wanted to test getting an Critically State. as test i did a unless eq ="1"

But it's staying at OK.

i added following:
```
my $AllStatus=".1.3.6.1.4.1.10876.2";

my $AllStatusColumns = {

	"2" => "Status",

	"3" => "Message"

};

my $AllHealth = getHashFromSNMP($session, $AllStatus, $AllStatusColumns);


for my $Health (@{$AllHealth}) {

push @criticals, ("Message : $Health->{'Message'}") unless $Health->{'Status'} eq "1";


}
```
thx

Max

**Comment by mintsoft** [comment]
I'll have to try this myself on Monday. I can't see any reason why this wouldn't just work
