### ISSUE TITLE
Adding CPU Status

### ISSUE THREAD

**Issue by madmax01** [mintsoft/check_supermicro_superdoctor#3]
Hi,

i tried to find out if all Main Components are inside the Monitoring.  

systemTree = .1.3.6.1.4.1.10876.2.1.1.1.1

For this systemtree seems i don't see the CPU Status checks. just seeing the voltage,temperature etc,....

i found this oid Tree for CPU: .1.3.6.1.4.1.10876.100.1.2.1

SNMPv2-SMI::enterprises.10876.100.1.2.1.1.1 = STRING: "1"
SNMPv2-SMI::enterprises.10876.100.1.2.1.2.1 = STRING: "Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz "
SNMPv2-SMI::enterprises.10876.100.1.2.1.3.1 = STRING: "Intel Xeon processor Family 6 Model 63 Stepping 2"
SNMPv2-SMI::enterprises.10876.100.1.2.1.4.1 = STRING: "GenuineIntel"
SNMPv2-SMI::enterprises.10876.100.1.2.1.5.1 = INTEGER: 0
SNMPv2-SMI::enterprises.10876.100.1.2.1.6.1 = STRING: "null"
SNMPv2-SMI::enterprises.10876.100.1.2.1.7.1 = STRING: "3500"
SNMPv2-SMI::enterprises.10876.100.1.2.1.9.1 = STRING: "null"
SNMPv2-SMI::enterprises.10876.100.1.2.1.10.1 = INTEGER: 6
SNMPv2-SMI::enterprises.10876.100.1.2.1.11.1 = INTEGER: 12
SNMPv2-SMI::enterprises.10876.100.1.2.1.12.1 = INTEGER: 6
SNMPv2-SMI::enterprises.10876.100.1.2.1.14.1 = STRING: "CPU1"
SNMPv2-SMI::enterprises.10876.100.1.2.1.18.1 = STRING: "Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz"

**Comment by mintsoft** [comment]
If that's what superdoctor provides, that's all there is. The plugin can only check things that are there unfortunately.
