### ISSUE TITLE
LSI OID not same for all Models

### ISSUE THREAD

**Issue by madmax01** [mintsoft/check_supermicro_superdoctor#4]
Hi,

i got a new Supermicro Server.  and this one is having an Intel + LSI Controleller.

i integrated checks for Intel all good.  but now wanted to integrate the LSI check for AOM-S3108M-H8L-P which is based on the LSI 3108 Chip.  i integrated the CIM Provider.

Instead of 1.3.6.1.4.1.10876.100.1.11.1  i had to give 1.3.6.1.4.1.3582.4.1.4.3.1.2.1

But now i'am getting an strange Error Back:

Modification of non-creatable array value attempted, subscript -1 at

is see its the Line $health->[$index-1]->{$columns->{$counter}} = $snmpResult->{$oid};

Not sure what i need to check.

if i do simple snmp walk i get the Values back without issues.

i see that there are some "-1" Integers

SNMPv2-SMI::enterprises.3582.4.1.4.3.1.2.1.1.0 = INTEGER: 0
SNMPv2-SMI::enterprises.3582.4.1.4.3.1.2.1.2.0 = INTEGER: 72089472
SNMPv2-SMI::enterprises.3582.4.1.4.3.1.2.1.3.0 = INTEGER: -1
SNMPv2-SMI::enterprises.3582.4.1.4.3.1.2.1.4.0 = INTEGER: 0
SNMPv2-SMI::enterprises.3582.4.1.4.3.1.2.1.5.0 = INTEGER: 3
SNMPv2-SMI::enterprises.3582.4.1.4.3.1.2.1.6.0 = STRING: "VD_0"
SNMPv2-SMI::enterprises.3582.4.1.4.3.1.2.1.24.0 = INTEGER: -1
SNMPv2-SMI::enterprises.3582.4.1.4.3.1.2.1.25.0 = INTEGER: -1

Could you please let me know how i could get the script working with that negative values?

Thx

Max

**Comment by mintsoft** [comment]
The problem here is most likely that the values don't have the same values as the columns on the hardware I've got (https://github.com/mintsoft/check_supermicro_superdoctor/blob/master/check_supermicro_superdoctor.pl#L66) if you snmpwalk both hardware you should be able to map the ID's.
